name: Build CV (Pandoc) and Publish to Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'cv/**'
      - '.github/workflows/build-cv.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Debug: confirm paths
      - name: Show repo layout
        run: |
          pwd
          ls -la
          echo "--- cv dir ---"
          ls -la ./cv || true

      - name: Install Pandoc and TeX
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive texlive-latex-recommended texlive-latex-extra

      - name: Build HTML CV (explicit paths; no working-directory)
        run: |
          test -f ./cv/cv.tex || { echo "cv/cv.tex not found"; exit 1; }
          pandoc ./cv/cv.tex -o ./cv/index.html \
            --standalone \
            --css ./cv/style.css \
            --citeproc \
            --bibliography=./cv/refs.bib \
            --metadata title="Vinny Gupta — CV"

      - name: Upload artifact (publish the cv/ folder)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./cv

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
